### ISSUE TITLE
feat(ci): set up pre-commit test and lint workflow

### ISSUE THREAD

**Issue by ChrisPuh** [ChrisPuh/lawn-management#1]
## Description
We need to implement automated testing and linting checks that run before each commit to ensure code quality and prevent bugs from entering the codebase.

## Tasks
- [ ] Install PHP_CodeSniffer for PHP linting
- [ ] Install ESLint and Stylelint for JavaScript/CSS linting
- [ ] Configure pre-commit hook with Husky
- [ ] Set up Laravel test environment
- [ ] Add test scripts to package.json
- [ ] Update README with testing documentation

## Implementation Details
1. PHPUnit Tests:
```bash
composer require --dev phpunit/phpunit

PHP_CodeSniffer:

bashCopycomposer require --dev squizlabs/php_codesniffer

ESLint & Stylelint:

bashCopynpm install --save-dev eslint stylelint

Pre-commit hook content:

bashCopy#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# PHP Tests
php artisan test --parallel

# PHP Linting
./vendor/bin/phpcs

# JavaScript Linting
npm run lint
Acceptance Criteria

 All tests must pass before commits are accepted
 PHP files must follow PSR-12 standards
 JavaScript/CSS files must follow defined style guides
 Clear documentation for developers on how to work with the test setup
 Fast execution to not hinder development workflow

Labels

type: enhancement
area: config
priority: high

Copy
Dieses Issue können wir direkt mit dem GitHub CLI Tool erstellen:
```bash
gh issue create --title "feat(ci): set up pre-commit test and lint workflow" --body-file issue.md --label "enhancement,config"
